sap.ui.define([
    // ============================================================
    // UIComponent
    // ------------------------------------------------------------
    // Base class for every SAPUI5 application component.
    // It provides:
    // - Lifecycle methods (init, destroy, etc.)
    // - Model management
    // - Router initialization
    // - Component-level configuration
    // ============================================================
    "sap/ui/core/UIComponent",

    // ============================================================
    // models.js
    // ------------------------------------------------------------
    // Custom utility file generated by Fiori tools.
    // Typically contains:
    // createDeviceModel()
    //
    // Device model helps UI adapt based on:
    // - Desktop
    // - Tablet
    // - Phone
    //
    // Example:
    // {
    //    system : {
    //       phone : false,
    //       tablet : false,
    //       desktop : true
    //    }
    // }
    // ============================================================
    "demo/mock/mockserver/model/models",

    // ============================================================
    // OData V2 Model
    // ------------------------------------------------------------
    // Since we converted metadata from OData V4 to OData V2,
    // we use the OData V2 model.
    //
    // Responsibilities:
    // - Calls $metadata
    // - Reads Employee data
    // - Reads Department data
    // - Handles CRUD operations
    //
    // Example URLs:
    // /odata/v2/service/$metadata
    // /odata/v2/service/Employees
    // /odata/v2/service/Departments
    // ============================================================
    "sap/ui/model/odata/v2/ODataModel",

    // ============================================================
    // Mock Server
    // ------------------------------------------------------------
    // Local fake backend.
    //
    // Reads:
    // localService/metadata.xml
    //
    // Generates:
    // /odata/v2/service/$metadata
    // /odata/v2/service/Employees
    // /odata/v2/service/Departments
    //
    // Reads mock data from:
    // localService/mockdata/*.json
    // ============================================================
    "./localService2/mockserver"

], (
    UIComponent,
    models,
    ODataModel,
    mockserver
) => {

    "use strict";

    // ============================================================
    // Application Component
    // ============================================================
    return UIComponent.extend(
        "demo.mock.mockserver.Component",
        {

            // ========================================================
            // Metadata Section
            // --------------------------------------------------------
            // manifest : "json"
            // tells UI5 to load manifest.json automatically.
            //
            // IAsyncContentCreation
            // enables asynchronous view creation
            // for better application startup performance.
            // ========================================================
            metadata: {
                manifest: "json",
                interfaces: [
                    "sap.ui.core.IAsyncContentCreation"
                ]
            },

            // ========================================================
            // init()
            // --------------------------------------------------------
            // Entry point of the application.
            //
            // Execution Order:
            //
            // 1. Start Mock Server
            // 2. Create OData Model
            // 3. Attach OData Model to Component
            // 4. Call Parent UIComponent init()
            // 5. Create Device Model
            // 6. Initialize Router
            // ========================================================
            init() {

                // ====================================================
                // STEP 1
                // Start Mock Server BEFORE creating ODataModel.
                //
                // Why?
                //
                // Earlier problem:
                //
                // App Started
                //      ↓
                // ODataModel Created
                //      ↓
                // GET $metadata
                //      ↓
                // 404 Error
                //      ↓
                // MockServer Started
                //
                // Result:
                // No data in UI
                //
                // Current Flow:
                //
                // App Started
                //      ↓
                // MockServer Started
                //      ↓
                // ODataModel Created
                //      ↓
                // $metadata intercepted
                //      ↓
                // Success
                // ====================================================
                mockserver.init();

                // ====================================================
                // STEP 2
                // Create ODataModel manually.
                //
                // Service Root URL:
                // /odata/v2/service/
                //
                // MockServer intercepts requests to:
                //
                // /odata/v2/service/$metadata
                // /odata/v2/service/Employees
                // /odata/v2/service/Departments
                //
                // useBatch:false
                // makes every request directly without $batch
                //
                // Easier for learning and debugging.
                // ====================================================
                var oModel = new ODataModel(
                    "/odata/v2/service/",
                    {
                        useBatch: false
                    }
                );

                // ====================================================
                // STEP 3
                // Attach OData model as default application model.
                //
                // Now all views can consume:
                //
                // {/Employees}
                // {/Departments}
                //
                // without explicitly referring to a model name.
                // ====================================================
                this.setModel(oModel);

                // ====================================================
                // STEP 4
                // Call parent UIComponent initialization.
                //
                // Loads:
                // - manifest.json
                // - routing configuration
                // - component lifecycle setup
                // ====================================================
                UIComponent.prototype.init.apply(
                    this,
                    arguments
                );

                // ====================================================
                // STEP 5
                // Create Device Model.
                //
                // Example Usage:
                //
                // visible="{device>/system/phone}"
                //
                // Helps create responsive applications.
                // ====================================================
                this.setModel(
                    models.createDeviceModel(),
                    "device"
                );

                // ====================================================
                // STEP 6
                // Start Router.
                //
                // Reads routing information from manifest.json.
                //
                // Example:
                //
                // RouteView1
                //      ↓
                // TargetView1
                //      ↓
                // View1.view.xml
                //
                // Without initialize(),
                // navigation will not work.
                // ====================================================
                this.getRouter().initialize();

                // ====================================================
                // Debugging Examples
                // Uncomment when needed
                // ====================================================

                /*
                console.log("Application Started");

                console.log(
                    "OData Model:",
                    this.getModel()
                );

                console.log(
                    "Device Model:",
                    this.getModel("device")
                );
                */

            }
        }
    );
});